#!/usr/share/ucs-test/runner python3
## desc: groups/group recursion due setting self as memberOf in group which already is member of self during modification
## tags: [udm]
## roles: [domaincontroller_master]
## bugs: [13008]
## exposure: careful
## packages:
##   - univention-config
##   - univention-directory-manager-tools


import sys
import univention.testing.utils as utils
import univention.testing.udm as udm_test

if __name__ == '__main__':
	with udm_test.UCSTestUDM() as udm:
		group = udm.create_group()[0]
		group2 = udm.create_group(memberOf=group)[0]

		try:
			udm.modify_object('groups/group', dn=group, memberOf=group2)
		except udm_test.UCSTestUDM_ModifyUDMObjectFailed:
			sys.exit(0)

		utils.fail('UDM did not report an error while trying to set a groups/group nestedGroup to itself during modification')
